version: '3.7'
services:
# Catalog Storefront app container (magento/catalog-storefront-ce repo)
  catalog:
    image: rkostiv/php-with-rr-grpc
    hostname: catalog
    working_dir: /var/www/catalog-storefront
    ports:
      - "228:22" #ssh
      - "9002:9001" # grpc
    stop_signal: SIGKILL
    env_file:
      - ../.env
    volumes:
      - code:/var/www
      - ../etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../etc/php/tools:/usr/local/bin/magento2:ro
      - ../etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    environment:
      COMPOSER_HOME: /var/www/.composer
      PHP_IDE_CONFIG: serverName=catalog
    command: sh -c 'service ssh start; php-fpm -R'
