version: '3.7'
services:
# To work with GraphQL server
  graphql:
    image: node:12.14.1-buster-slim
    command: sh -c 'npm ci && npm run build && ./bin/magento-graphql start '
    tty: true
    working_dir: /var/www/graphql
    env_file:
      - ../.env
    volumes:
      - code:/var/www
    environment:
      - MONOLITH_GRAPHQL_URL=http://magento.test/graphql
      - LOG_FILE=/var/www/graphql/app.log
      - ENABLE_CATALOG_STOREFRONT=true
      - CATALOG_STOREFRONT_HOST=app
      - CATALOG_STOREFRONT_PORT=9001
    ports:
      - 8008:8008