version: '3.7'
services:
  grpcui-monolith:
    image: wongnai/grpcui
    ports:
      - "8080:8080"
    volumes:
      - code:/var/www
    entrypoint: ["grpcui", "-plaintext", "-proto", "magento.proto", "-port", "8080", "-bind", "0.0.0.0", "-import-path", "/var/www/magento2ce", "app:9001"]

  grpcui-catalog:
    image: wongnai/grpcui
    ports:
      - "8081:8081"
    volumes:
      - code:/var/www
    entrypoint: ["grpcui", "-plaintext", "-proto", "magento.proto", "-port", "8081", "-bind", "0.0.0.0", "-import-path", "/var/www/magento2ce", "app-catalog-storefront:9001"]

  grpcui-search:
    image: wongnai/grpcui
    ports:
      - "8082:8082"
    volumes:
      - ${MAGENTO_PATH}/storefront-search-ce:/var/www/app
    entrypoint: ["grpcui", "-plaintext", "-proto", "search.proto", "-port", "8082", "-bind", "0.0.0.0", "-import-path", "/var/www/storefront-search-ce", "app-search:9001"]

  grpcui-product-reviews:
    image: wongnai/grpcui
    ports:
      - "8083:8083"
    volumes:
      - ${MAGENTO_PATH}/storefront-product-reviews-ce:/var/www/app
    entrypoint: ["grpcui", "-plaintext", "-proto", "reviews.proto", "-port", "8083", "-bind", "0.0.0.0", "-import-path", "/var/www/app", "app-product-reviews:9001"]


  grpcui-pricing:
    image: wongnai/grpcui
    ports:
      - "8084:8084"
    volumes:
      - ${MAGENTO_PATH}/storefront-pricing-ce:/var/www/app
    entrypoint: ["grpcui", "-plaintext", "-proto", "pricing.proto", "-port", "8084", "-bind", "0.0.0.0", "-import-path", "/var/www/app", "app-product-reviews:9001"]

