version: '3.7'
services:
  # Storefront Search app container (magento/storefront-search-ce repo)
  app-search:
    image: rkostiv/php-with-rr-grpc
    hostname: app-search
    working_dir: /var/www/storefront-search-ce
    ports:
      - "226:22" #ssh
    stop_signal: SIGKILL
    env_file:
      - ../.env
    volumes:
      - code:/var/www
      - ../etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../etc/php/tools:/usr/local/bin/magento2:ro
      - ../etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    environment:
      COMPOSER_HOME: /var/www/.composer
      PHP_IDE_CONFIG: serverName=app-search
    command: sh -c 'service ssh start; php-fpm -R'